[package]
name = "heim-virt"
version = "0.0.3"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform virtualization system detection"
keywords = ["heim", "system", "information"]
categories = ["asynchronous", "os"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
heim-common = { version = "0.0.3", path = "../heim-common" }
cfg-if = "0.1.9"

[target.'cfg(target_os = "linux")'.dependencies]
raw-cpuid = "6.1.0"

[dev-dependencies]
runtime = "0.3.0-alpha.6"
tempfile = "3.0"

[features]
doc = []

[package.metadata.docs.rs]
features = ["doc"]
